# Generated by Django 4.1.5 on 2023-01-08 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FloatField(verbose_name='Ответ')),
                ('is_correct', models.BooleanField(default=None, null=True, verbose_name='Правильно ответили?')),
                ('answer_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Когда ответили? (UTC+5)')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название олимпиады')),
                ('description', models.CharField(max_length=600, verbose_name='Описание олимпиады')),
                ('olympiad_level', models.CharField(choices=[('1', '1 тур'), ('2', '2 тур - основной уровень'), ('3', '2 тур - высший уровень')], max_length=1, unique=True)),
                ('image_url', models.CharField(help_text="Загрузите её на imgur.com/upload После этого правым кликом мыши нажмите по фото и кликните 'Копировать ссылку на изображение'. Вставьте ссылку. Пример: https://i.imgur.com/sRjy27f.jpg", max_length=300, verbose_name='Ссылка на обложку олимпиады')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Олимпиада создана')),
                ('start_time', models.DateTimeField(verbose_name='Время старта олимпиады')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания олимпиады')),
            ],
            options={
                'verbose_name': 'Олимпиада',
                'verbose_name_plural': 'Олимпиады',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок задания')),
                ('text', models.TextField(verbose_name='Текст задания')),
                ('correct_answer', models.FloatField(help_text='Доступен только ввод числа, например: 1,35 или 17', verbose_name='Правильный ответ')),
                ('image_url', models.CharField(blank=True, help_text="Если в постановке задания требуется иллюстрация, то загрузите её на imgur.com/upload После этого правым кликом мыши нажмите по фото и кликните 'Копировать ссылку на изображение'. Вставьте ссылку. Пример: https://i.imgur.com/sRjy27f.jpg", max_length=200, verbose_name='Ссылка на иллюстрацию')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Задание создано')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.olympiad', verbose_name='Олимпиада')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='olympiad',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='end_time__gt__start_time'),
        ),
        migrations.AddField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Команда'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('task', 'user')},
        ),
    ]
