# Generated by Django 4.1.5 on 2023-01-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='olympiad',
            name='end_time__gt__start_time',
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='olympiad_level',
            field=models.CharField(choices=[('1', '1 тур'), ('2', '2 тур - основной уровень'), ('3', '2 тур - высший уровень')], max_length=1, unique=True, verbose_name='Тур олимпиады'),
        ),
        migrations.AddConstraint(
            model_name='olympiad',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='Время окончания должно быть позже времени старта'),
        ),
    ]
