# Generated by Django 4.1.5 on 2023-01-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_olympiad_end_time__gt__start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильно ответили?'),
            preserve_default=False,
        ),
    ]
