# Generated by Django 4.1.5 on 2023-02-01 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_alter_olympiad_olympiad_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Когда приступили к выполнению? (UTC+5)')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Когда закончили выполнять? (UTC+5)')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.olympiad', verbose_name='Олимпиада')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Время прохождения',
                'unique_together': {('olympiad', 'user')},
            },
        ),
    ]
