# Generated by Django 4.1.5 on 2023-02-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_timetrack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetrack',
            options={'verbose_name': 'Время прохождения', 'verbose_name_plural': 'Время прохождения'},
        ),
    ]
